# docker-compose.yml
version: '3.0'

services:
  mysql:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: myrootpw
      MYSQL_DATABASE: gallery3
      MYSQL_USER: gallery3
      MYSQL_PASSWORD: mygallery3pw
    volumes:
      - ./mysql:/var/lib/mysql
  gallery3:
    image: bwdutton/gallery3
#    build:
#      context: .
#      dockerfile: Dockerfile
    environment:
# set these if you wish to use the CLI installer, otherwise you enter them on the web
      MYSQL_ROOT_PASSWORD: myrootpw
      MYSQL_DATABASE: gallery3
      MYSQL_USER: gallery3
      MYSQL_PASSWORD: mygallery3pw
      MYSQL_HOST: mysql
      G3_PASSWORD:
      DB_PREFIX:
      SITE_DOMAIN:
      SITE_PROTOCOL:
    ports:
      - "80:80"
    volumes:
      - ./gallery-var:/var/www/var
